using System;

[Serializable]
public class PlayerData
{
    public string Player { get; set; }
    public string Team { get; set; }
    public string Position { get; set; }
    public int Salary { get; set; }
    public double Minutes { get; set; }
    public double Max_Minutes { get; set; }  // Matches "Max Minutes" in CSV
    public double MIN_CUM_AVG { get; set; }
    public double MIN_LAST_3_AVG { get; set; }
    public double MIN_LAST_5_AVG { get; set; }
    public double MIN_LAST_10_AVG { get; set; }
    public double MIN_TREND { get; set; }
    public double MIN_CONSISTENCY { get; set; }
    public double MIN_CONSISTENCY_SCORE { get; set; }
    public double MIN_ABOVE_20 { get; set; }
    public double MIN_ABOVE_25 { get; set; }
    public double MIN_ABOVE_30 { get; set; }
    public double MIN_ABOVE_AVG_STREAK { get; set; }
    public double FREQ_ABOVE_20 { get; set; }
    public double FREQ_ABOVE_25 { get; set; }
    public double FREQ_ABOVE_30 { get; set; }
    public double Projected_Pts { get; set; }  // Matches "Projected Pts" in CSV
    public double DK { get; set; }
    public double DK_CUM_AVG { get; set; }
    public double DK_LAST_3_AVG { get; set; }
    public double DK_LAST_5_AVG { get; set; }
    public double DK_LAST_10_AVG { get; set; }
    public double DK_TREND { get; set; }
    public double DK_TREND_5 { get; set; }
    public double DK_CONSISTENCY { get; set; }
    public double PTS_LAST_3_AVG { get; set; }
    public double PTS_LAST_5_AVG { get; set; }
    public double PTS_LAST_10_AVG { get; set; }
    public double REB_LAST_3_AVG { get; set; }
    public double REB_LAST_5_AVG { get; set; }
    public double REB_LAST_10_AVG { get; set; }
    public double AST_LAST_3_AVG { get; set; }
    public double AST_LAST_5_AVG { get; set; }
    public double AST_LAST_10_AVG { get; set; }
    public double PTS_CUM_AVG { get; set; }
    public double REB_CUM_AVG { get; set; }
    public double AST_CUM_AVG { get; set; }
    public double PTS_PER_MIN { get; set; }
    public double REB_PER_MIN { get; set; }
    public double AST_PER_MIN { get; set; }
    public double SCORING_EFFICIENCY { get; set; }
    public double RECENT_SCORING_EFF { get; set; }
    public double FG_PCT { get; set; }
    public double FG3_PCT { get; set; }
    public double FT_PCT { get; set; }
    public double FGM { get; set; }
    public double FGA { get; set; }
    public double FG3M { get; set; }
    public double FG3A { get; set; }
    public double FTM { get; set; }
    public double FTA { get; set; }
    public double PLUS_MINUS { get; set; }
    public double PLUS_MINUS_PER_MIN { get; set; }
    public double PLUS_MINUS_LAST_3_AVG { get; set; }
    public double PLUS_MINUS_LAST_5_AVG { get; set; }
    public double PLUS_MINUS_LAST_10_AVG { get; set; }
    public double PLUS_MINUS_CUM_AVG { get; set; }
    public double PLUS_MINUS_TREND { get; set; }
    public double PLUS_MINUS_CONSISTENCY { get; set; }
    public double PTS_TREND { get; set; }
    public double REB_TREND { get; set; }
    public double AST_TREND { get; set; }
    public double PTS_CONSISTENCY { get; set; }
    public double REB_CONSISTENCY { get; set; }
    public double AST_CONSISTENCY { get; set; }
    public double TEAM_MIN_PERCENTAGE { get; set; }
    public double TEAM_PROJ_RANK { get; set; }
    public double PTS_VS_TEAM_AVG { get; set; }
    public double REB_VS_TEAM_AVG { get; set; }
    public double AST_VS_TEAM_AVG { get; set; }
    public double MIN_VS_TEAM_AVG { get; set; }
    public double ROLE_CHANGE_3_10 { get; set; }
    public double ROLE_CHANGE_5_10 { get; set; }
    public double IS_TOP_3_PROJ { get; set; }
    public double LOW_MIN_TOP_PLAYER { get; set; }
    public DateTime? GAME_DATE { get; set; }
    public double IS_HOME { get; set; }
    public double IS_B2B { get; set; }
    public double DAYS_REST { get; set; }
    public string MATCHUP { get; set; }
    public string WL { get; set; }
    public double BLOWOUT_GAME { get; set; }
    public double STL { get; set; }
    public double BLK { get; set; }
    public double TOV { get; set; }
    public double OREB { get; set; }
    public double DREB { get; set; }
    public double PF { get; set; }
    public double PLAYER_ID { get; set; }
    public double TEAM_ID { get; set; }
    public string TEAM_NAME { get; set; }
    public double GAME_ID { get; set; }
    public double SEASON_ID { get; set; }
    public double VIDEO_AVAILABLE { get; set; }
}